/**
 * TopStoriesWebsites.com - Verified Media Inventory Data
 * Structured database of pre-audited digital news assets.
 * Confidentiality Protection: Domain identities are strictly masked (e.g. h***n***s.com)
 * Full unredacted domain names, analytics access, and GSC logs are released only under signed NDA.
 */

const LISTINGS_DATA = [
  {
    id: "TSW-101",
    title: "Global Financial Markets & Tech Wire",
    domainSlug: "f***t***w***.com (Verified Under NDA)",
    category: "google-news",
    categoryLabel: "Google News Approved",
    badgeType: "badge-cyan",
    price: 38500,
    priceFormatted: "$38,500",
    monthlyNet: "$1,620 / mo",
    monthlyNetNum: 1620,
    multiple: "23.7x Net",
    indexingSpeed: "65 seconds",
    indexingSpeedNum: 65,
    domainAge: "6 Years (2018)",
    monthlyVisitors: "145,000",
    googleDiscoverActive: true,
    topStoriesActive: true,
    bingApproved: true,
    yahooNews: false,
    publisherCenterStatus: "Grandfathered Instant-Index Publication",
    features: [
      "Instant RSS Feed Ingestion (under 75s avg)",
      "High Authority Backlink Profile (DR 54 / DA 48)",
      "Google Discover Traffic Enabled (US/UK Focus)",
      "Clean Google Search Console Manual Actions Log"
    ],
    monetization: "Google AdSense + Premium Header Bidding"
  },
  {
    id: "TSW-102",
    title: "National Automotive & EV Daily",
    domainSlug: "a***c***m***.org (Verified Under NDA)",
    category: "google-discover",
    categoryLabel: "Google Discover Dominated",
    badgeType: "badge-purple",
    price: 64000,
    priceFormatted: "$64,000",
    monthlyNet: "$2,850 / mo",
    monthlyNetNum: 2850,
    multiple: "22.4x Net",
    indexingSpeed: "90 seconds",
    indexingSpeedNum: 90,
    domainAge: "8 Years (2016)",
    monthlyVisitors: "320,000",
    googleDiscoverActive: true,
    topStoriesActive: true,
    bingApproved: true,
    yahooNews: false,
    publisherCenterStatus: "Active Publisher Center Approved",
    features: [
      "Consistent 180k+ Monthly Discover Impressions",
      "Mediavine / Raptive Approved & Running",
      "Verified Google Top Stories Carousel Presence",
      "100% Organic Editorial Workflow Included"
    ],
    monetization: "Mediavine Ad Network (RPM $24-$38)"
  },
  {
    id: "TSW-103",
    title: "Tier-1 Entertainment & Pop Culture Desk",
    domainSlug: "h***w***b***.com (Verified Under NDA)",
    category: "top-stories",
    categoryLabel: "Top Stories Carousel Ranker",
    badgeType: "badge-amber",
    price: 92000,
    priceFormatted: "$92,000",
    monthlyNet: "$4,100 / mo",
    monthlyNetNum: 4100,
    multiple: "22.4x Net",
    indexingSpeed: "45 seconds",
    indexingSpeedNum: 45,
    domainAge: "9 Years (2015)",
    monthlyVisitors: "580,000",
    googleDiscoverActive: true,
    topStoriesActive: true,
    bingApproved: true,
    yahooNews: true,
    publisherCenterStatus: "Grandfathered News Entity (High Trust Authority)",
    features: [
      "Ranks in Google Top Stories within 3 mins of breaking news",
      "Direct Yahoo News Syndication Gateway Enabled",
      "Domain Rating 61 (Includes Forbes, Variety backlinks)",
      "Clean Escrow.com Ready Domain Auth Transfer"
    ],
    monetization: "Header Bidding + Sponsored Press Releases"
  },
  {
    id: "TSW-104",
    title: "Healthcare Innovations & Wellness Gazette",
    domainSlug: "h***p***j***.com (Verified Under NDA)",
    category: "google-news",
    categoryLabel: "Google News Approved",
    badgeType: "badge-cyan",
    price: 24500,
    priceFormatted: "$24,500",
    monthlyNet: "$1,080 / mo",
    monthlyNetNum: 1080,
    multiple: "22.6x Net",
    indexingSpeed: "110 seconds",
    indexingSpeedNum: 110,
    domainAge: "5 Years (2019)",
    monthlyVisitors: "95,000",
    googleDiscoverActive: false,
    topStoriesActive: true,
    bingApproved: true,
    yahooNews: false,
    publisherCenterStatus: "Verified Publisher Center Publication",
    features: [
      "Established Medical/Science News Entity Schema",
      "Active Bing News PubHub Acceptance",
      "E-E-A-T Medical Reviewers Schema Structure",
      "Turnkey WordPress News Editorial CMS"
    ],
    monetization: "AdSense + Direct Affiliate Sponsorships"
  },
  {
    id: "TSW-105",
    title: "European Business & Crypto Chronicle",
    domainSlug: "e***f***c***.eu (Verified Under NDA)",
    category: "bing-news",
    categoryLabel: "Bing & Google News Approved",
    badgeType: "badge-emerald",
    price: 49000,
    priceFormatted: "$49,000",
    monthlyNet: "$2,200 / mo",
    monthlyNetNum: 2200,
    multiple: "22.2x Net",
    indexingSpeed: "80 seconds",
    indexingSpeedNum: 80,
    domainAge: "7 Years (2017)",
    monthlyVisitors: "210,000",
    googleDiscoverActive: true,
    topStoriesActive: false,
    bingApproved: true,
    yahooNews: false,
    publisherCenterStatus: "Dual Google & Bing Newsstand Verified",
    features: [
      "Bing Webmaster IndexNow Protocol Fully Configured",
      "High European Tier-1 Traffic Demographics",
      "Google Discover Interest Nodes: Fintech & Web3",
      "Includes Verified Google Analytics 4 & GSC Records"
    ],
    monetization: "Cryptocurrency Press Release Wire + AdSense"
  },
  {
    id: "TSW-106",
    title: "North America Metro News Syndicate",
    domainSlug: "u***m***n***.com (Verified Under NDA)",
    category: "yahoo-news",
    categoryLabel: "Yahoo & Google News Network",
    badgeType: "badge-cyan",
    price: 135000,
    priceFormatted: "$135,000",
    monthlyNet: "$5,800 / mo",
    monthlyNetNum: 5800,
    multiple: "23.2x Net",
    indexingSpeed: "40 seconds",
    indexingSpeedNum: 40,
    domainAge: "11 Years (2013)",
    monthlyVisitors: "840,000",
    googleDiscoverActive: true,
    topStoriesActive: true,
    bingApproved: true,
    yahooNews: true,
    publisherCenterStatus: "Legacy High-Trust Media Entity",
    features: [
      "Direct Yahoo News & MSN News Partner Feed",
      "Sub-60s Google Top Stories Carousel Capture",
      "Google Newsstand Subscriber Base: 28,000+",
      "Full Transfer of GSC, Google News Org, & CMS"
    ],
    monetization: "Direct Programmatic SSPs + Sponsored Stories"
  },
  {
    id: "TSW-107",
    title: "Gaming & Esports Live Wire",
    domainSlug: "e***s***r***.gg (Verified Under NDA)",
    category: "google-discover",
    categoryLabel: "Google Discover Active",
    badgeType: "badge-purple",
    price: 32000,
    priceFormatted: "$32,000",
    monthlyNet: "$1,450 / mo",
    monthlyNetNum: 1450,
    multiple: "22.0x Net",
    indexingSpeed: "95 seconds",
    indexingSpeedNum: 95,
    domainAge: "4 Years (2020)",
    monthlyVisitors: "175,000",
    googleDiscoverActive: true,
    topStoriesActive: true,
    bingApproved: true,
    yahooNews: false,
    publisherCenterStatus: "Verified Publisher Center Entity",
    features: [
      "Consistent Spike Traffic on Major Gaming Releases",
      "Strong Mobile Engagement Signals (Avg Dwell 2m 40s)",
      "Automated Steam/Twitch API Integration Hooks",
      "Passes Core Web Vitals 100/100 on Mobile"
    ],
    monetization: "Ezoic Premium / AdSense"
  },
  {
    id: "TSW-108",
    title: "Green Energy & CleanTech Observer",
    domainSlug: "c***t***o***.com (Verified Under NDA)",
    category: "google-news",
    categoryLabel: "Google News Approved",
    badgeType: "badge-cyan",
    price: 28000,
    priceFormatted: "$28,000",
    monthlyNet: "$1,250 / mo",
    monthlyNetNum: 1250,
    multiple: "22.4x Net",
    indexingSpeed: "120 seconds",
    indexingSpeedNum: 120,
    domainAge: "5 Years (2019)",
    monthlyVisitors: "88,000",
    googleDiscoverActive: false,
    topStoriesActive: true,
    bingApproved: true,
    yahooNews: false,
    publisherCenterStatus: "Google Publisher Center Active",
    features: [
      "ESG Corporate Press Release High-CPM Ingestion",
      "B2B Editorial Backlink Profile from Clean Energy Orgs",
      "No Algorithmic Penalties or Search Drops",
      "Ready for Instant Escrow Transfer"
    ],
    monetization: "B2B Sponsored Content + Google AdSense"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = LISTINGS_DATA;
}
